# Generated by Django 3.0.4 on 2020-03-14 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='File')),
                ('caption', models.CharField(max_length=50, verbose_name='Caption')),
                ('access', models.CharField(choices=[('0', 'Public'), ('1', 'Hidden'), ('2', 'Private')], default='0', max_length=20, verbose_name='Access')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
