# Generated by Django 3.0.4 on 2020-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='access',
            field=models.CharField(choices=[('Public', 'Публичный'), ('Hidden', 'Скрытый'), ('Private', 'Приватный')], default='Public', max_length=20, verbose_name='Access'),
        ),
    ]
